spring.application.name=library-management-system
spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT:8080}

# MySQL Connection
# database properties -> used to connect to mysql database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/library_management_system}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
# for automatically update database after every change
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
# Shows the SQL statements in the console for debugging
spring.jpa.show-sql=${SHOW_SQL:false}
